#### general settings

name: inn_train_32
use_tb_logger: true
model: MIMO-VRN-h
distortion: sr
scale: 4
gpu_ids: [0]
gop: 3
num_video: 1

#### datasets

datasets:
  train:
    name: Vimeo90K
    mode: train
    interval_list: [1]
    random_reverse: false
    border_mode: false
    video_path: /watermark/VideoSet
    audio_path: /watermark/AudioSet
    video_txt_path: /watermark/VideoSet.txt
    audio_txt_path: /watermark/AudioSet.txt
    dataroot_LQ: ~/vimeo90k/vimeo90k_train_LR7frames.lmdb
    audio_sample_rate: 16000
    hop_length: 200
    cache_keys: Vimeo90K_train_keys.pkl
    num_video: 1

    N_frames: 1
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4
    GT_size: 256
    LQ_size: 36
    use_flip: true
    use_rot: true
    color: RGB

  val:
    num_video: 1
    name: Vid4
    mode: test
    video_path: /watermark/DAVIS/JPEGImages/480p
    audio_path: /watermark/TestAudioSet
    sr_path: /watermark/E2FGVI/results2
    video_mask_path: /watermark/DAVIS/Annotations/480p
    video_txt_path: /watermark/DAVIS/ImageSets/2016/train.txt
    audio_txt_path: /watermark/DAVIS/ImageSets/2016/train.txt
    audio_sample_rate: 16000
    hop_length: 200
    txt_path: /home/aikusrv02/watermarking/test.txt

    N_frames: 1
    GT_size: 256
    LQ_size: 36
    padding: 'new_info'
    pred_interval: -1
    interval_list: [1]
    random_reverse: false


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_hi_nc: 1
  in_ho_nc: 2


  out_nc: 12
  block_num: [8,8]
  scale: 2
  init: xavier_group
  block_num_rbm: 8


#### path

path:
  pretrain_model_G: #/watermark/experiments/train_LF-VSN_1video/models
  pretrain_model_E: #/watermark/experiments/train_LF-VSN_1video/models
  models: ckp/base
  strict_load: true
  resume_state: #/watermark/experiments/train_LF-VSN_1video/training_state/60000.state
  val_images: #/watermark/Result


#### training settings: learning rate scheme, loss

train:

  lr_G: !!float 1e-3
  beta1: 0.9
  beta2: 0.5
  niter: 250000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [30000, 60000, 90000, 150000, 180000, 210000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 10

  val_freq: !!float 1500 #!!float 5e3

  lambda_fit_forw: 64.
  lambda_rec_back: 1
  lambda_center: 0

  weight_decay_G: !!float 1e-12
  gradient_clipping: 10


#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
