#### general settings

name: STFT_DWT_FACIAL_SHORT_RESHAPE2
use_tb_logger: true
model: MIMO-VRN-h
distortion: sr
scale: 4
gpu_ids: [4]
gop: 3
num_video: 1
moco_m : 0.999
chunk_size: 500
message_length: 640
audio_length: 1
fps: 25

#### datasets

datasets:
  train:
    name: Vimeo90K
    mode: train
    interval_list: [1]
    random_reverse: true
    border_mode: false
    txt_path: /watermark/HDTF_dataset/train.txt
    dataroot_LQ: ~/vimeo90k/vimeo90k_train_LR7frames.lmdb
    audio_sample_rate: 16000
    hop_length: 200
    cache_keys: Vimeo90K_train_keys.pkl
    num_video: 1

    fps: 25
    N_frames: 1
    use_shuffle: false
    n_workers: 4  # per GPU
    batch_size: 16
    audio_length: 1
    GT_size: 256
    LQ_size: 36
    use_flip: false
    use_rot: false
    color: RGB

  val:
    num_video: 1
    name: Vid4
    mode: test
    txt_path: /watermark/HDTF_dataset/test.txt
    audio_sample_rate: 16000
    hop_length: 200
    fps : 1

    N_frames: 1
    GT_size: 512
    LQ_size: 36
    padding: 'new_info'
    pred_interval: -1
    interval_list: [1]
    random_reverse: false


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_hi_nc: 1
  in_ho_nc: 48

  channel: 12
  out_nc: 12
  block_num: [8, 8]
  scale: 2
  init: xavier_group
  block_num_rbm: 8


#### path

path:
  pretrain_model_G: #/watermark/experiments/shuffle/models/100000_G.pth
  pretrain_model_M: #/watermark/experiments/shuffle/models/100000_E.pth
  models: ckp/base
  strict_load: true
  resume_state: #/watermark/experiments/shuffle/training_state/100000.state
  val_images: #/watermark/Result


#### training settings: learning rate scheme, loss

train:

  lr_G: !!float 1e-4
  lr_E: !!float 1e-4

  beta1: 0.9
  beta2: 0.5
  niter: 100000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [30000, 60000, 90000, 150000, 180000, 210000]
  lr_gamma: 0.5
  schedule: [120, 160]
  cos: false

  manual_seed: 10

  val_freq: !!float 5e3

  lambda_vrl: 0.1
  lambda_wl: 10
  lambda_arl: 10
  lambda_sfcl: 1

  weight_decay_G: !!float 1e-12
  weight_decay_E: !!float 1e-4
  gradient_clipping: 10


#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
